name: run-build

on:
  push:
    branches:
      - main

jobs:

  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: |
          pwd
          cd ${{ github.repository }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: npm run build

      - name: Switch to build branch
        run: git checkout build

      - name: Copy files
        run: cp "./dist/*" "./"

      - name: Commit files
        run: |
          git add *.d.ts
          git commit -m "Build for ${{ github.ref }}"
